pull_request_rules:
  - name: Automatic merge for Update dependencies
    conditions:
      - title=Update dependencies
      - check-success=pre-commit.ci - pr
      - check-success=test
    actions:
      merge:
        method: merge
