ci:
  skip: [pip-compile, mypy]
  autoupdate_schedule: 'monthly'
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/psf/black'
    rev: 24.4.2
    hooks:
      - id: black
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'v1.10.0'
    hooks:
      - id: mypy
  - repo: 'https://github.com/jazzband/pip-tools'
    rev: 7.4.1
    hooks:
      - id: pip-compile
        language_version: python3.12
        name: pip-compile requirements.in
        args: [requirements.in]
        files: ^requirements\.(in|txt)$
      - id: pip-compile
        language_version: python3.12
        name: pip-compile dev-requirements.txt
        args: [dev-requirements.in]
        files: ^dev-requirements\.(in|txt)$
