ci:
  skip: [mypy]
  autoupdate_schedule: 'monthly'
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'v1.18.2'
    hooks:
      - id: mypy
