ci:
  skip: [pip-compile, mypy]
  autoupdate_schedule: 'monthly'
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'v1.11.1'
    hooks:
      - id: mypy
  - repo: 'https://github.com/jazzband/pip-tools'
    rev: 7.4.1
    hooks:
      - id: pip-compile
        language_version: python3.12
        name: pip-compile requirements.in
        args: [requirements.in]
        files: ^requirements\.(in|txt)$
