# Generated by Django 6.0.2 on 2026-02-28 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Birthday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField(unique=True)),
                ("day", models.IntegerField()),
                ("month", models.IntegerField()),
            ],
            options={
                "db_table": "birthday",
            },
        ),
        migrations.CreateModel(
            name="Karma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.TextField()),
                ("ts", models.TextField()),
                ("user", models.TextField()),
                ("emoji", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "karma",
            },
        ),
    ]
