# Generated by Django 6.0.2 on 2026-03-01 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="birthday",
            table=None,
        ),
        migrations.AlterModelTable(
            name="karma",
            table=None,
        ),
    ]
