# Generated by Django 6.0.2 on 2026-03-01 13:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_birthday_table_alter_karma_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("is_private", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("display_name", models.TextField(blank=True, default="")),
                ("real_name", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_bot", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="karma",
            name="channel_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="karma_events",
                to="bot.channel",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.CharField(db_index=True, max_length=50)),
                ("thread_ts", models.CharField(blank=True, default="", max_length=50)),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot.slackuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "ts")},
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_file_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "original_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                ("filename", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="bot.message",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="karma",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="karma_events",
                to="bot.message",
            ),
        ),
        migrations.AddField(
            model_name="karma",
            name="giver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="karma_given",
                to="bot.slackuser",
            ),
        ),
        migrations.AddField(
            model_name="karma",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="karma_received",
                to="bot.slackuser",
            ),
        ),
    ]
