# Generated by Django 6.0.2 on 2026-03-01 13:30

from django.db import migrations


def backfill(apps, schema_editor):
    Karma = apps.get_model("bot", "Karma")
    SlackUser = apps.get_model("bot", "SlackUser")
    Channel = apps.get_model("bot", "Channel")

    # Create SlackUser records for all unique receivers
    user_ids = set(Karma.objects.values_list("user", flat=True).distinct())
    for slack_id in user_ids:
        SlackUser.objects.get_or_create(
            slack_id=slack_id, defaults={"display_name": slack_id}
        )

    # Create Channel records for all unique channels
    channel_ids = set(Karma.objects.values_list("channel", flat=True).distinct())
    for slack_id in channel_ids:
        Channel.objects.get_or_create(slack_id=slack_id, defaults={"name": slack_id})

    # Link karma records to receiver and channel_ref
    for karma in Karma.objects.select_related("receiver", "channel_ref").filter(
        receiver__isnull=True
    ):
        karma.receiver = SlackUser.objects.filter(slack_id=karma.user).first()
        karma.channel_ref = Channel.objects.filter(slack_id=karma.channel).first()
        karma.save(update_fields=["receiver", "channel_ref"])


def reverse_backfill(apps, schema_editor):
    Karma = apps.get_model("bot", "Karma")
    Karma.objects.update(receiver=None, channel_ref=None)


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_channel_slackuser_karma_channel_ref_message_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_backfill),
    ]
