# This workflow will install pip-tools, run pip-compile to update all dependencies and then
# open a PR unless everything is up to date.

name: Upgrade dependencies

on:
  schedule:
  - cron: "0 6 * * MON"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        version: "latest"
    - name: Upgrade dependencies
      run: uv lock --upgrade
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update dependencies
        branch: bot/update_dependencies
        delete-branch: true
        title: 'Update dependencies'
        body: New updates for project dependencies 🚀
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
